### ISSUE TITLE
output.sam contents

### ISSUE THREAD

**Issue by AssiaS** [gmiclotte/refalign#1]
het zou handig zijn moest de output.sam file die door de align.py geproduceerd wordt naast de cigar strings en posities ook de sequenties bevatten van de contigs

**Comment by gmiclotte** [comment]
Na commit 93481eceaac7e82bb02959af19400e0345191e7b zou dit moeten werken. Laat a.u.b. weten of dit aan de verwachtingen voldoet, of als er problemen zijn.

Met vriendelijke groeten,
Giles

**Comment by AssiaS** [comment]
Dag Giles,
Het produceerts alleszins al correcte sam files die normaal converteren nr
bam files enz, en op het eerste zicht zijn de resultaten hetgeen ik nodig
had. Ik ga er in de komende weken in meer detail naar kijken.
Merci!
Groetjes
Assia
